- name: installing frontend
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx 
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: remove default nginx
    ansible.builtin.file:
      path: /usr/share/nginx/html/*
      state: absent

  - name: download frontend application
    ansible.builtin.get_url: 
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip 

  - name: unarchive the url
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html

  - name: copy the expenses
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

  - name: restart the nginx 
    ansible.builtin.service:
       name: httpd
       state: started 
       enabled: yes


